paolabrb/dreamsbnb

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
I just added this footer, please review
> add footer

- app/views/layouts/application.html.erb
i just updated the navbar links
> updated navbar path

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/dreams_controller.rb
- app/controllers/pages_controller.rb
- app/policies/application_policy.rb
- app/policies/dream_policy.rb
- test/policies/dream_policy_test.rb
Hi girls, Pundit is up and running! Can you review?
> add Pundit gem, correct dreams#show and dreams#index with authorization

- app/controllers/dreams_controller.rb
- app/models/dream.rb
- app/views/dreams/new.html.erb
Please have a look at updated view for new dream
> updated new dream view

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
added background color to footer
and added test dreams
> added background-color

- .gitignore
- Gemfile
- Gemfile.lock
- app/views/dreams/show.html.erb
Upload Picture Done, without updating view.
> Upload pictures

- app/views/layouts/application.html.erb
I have added an avatar dropdown menu to the navbar.
Now:
if the user is logged in, it will show the avatar + log out & profile options
if the user is logged out, it will show sign up / log in options.
:smile:
> Add avatar menu to navbar

- app/assets/stylesheets/components/_form-create.scss
- app/assets/stylesheets/components/_index.scss
- app/views/dreams/new.html.erb
worked on the create form page
> made form bit smaller, add backgroundimg

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/dreams_controller.rb
- app/models/dream.rb
- app/uploaders/photo_uploader.rb
- app/views/dreams/new.html.erb
- config/routes.rb
- db/migrate/20191119160514_add_photo_to_dreams.rb
- db/schema.rb
Can you have a look and rewiev, thank u
> Upload picture

- app/views/layouts/application.html.erb
> switch log out and profile items in dropdown menu

- app/views/dreams/show.html.erb
Hello there :wave: 
I have updated the show page with Suzie's dreamy style :D
> update show page with Suzies style

- app/views/dreams/edit.html.erb
Edit page now has same style as "add" page :)
> update edit page with Suzies style

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_profile.scss
- app/controllers/pages_controller.rb
- app/views/pages/profile.html.erb
- db/schema.rb
the beginning of the dashboard
> start dashboard

- app/controllers/bookings_controller.rb
- app/policies/booking_policy.rb
- app/views/bookings/create.html.erb
- app/views/bookings/new.html.erb
- config/routes.rb
- db/migrate/20191119170918_add_information_to_bookings.rb
- db/schema.rb
- test/controllers/bookings_controller_test.rb
- test/policies/booking_policy_test.rb
- test/policies/bookings_policy_test.rb
Started to work on adding bookings to our app.
Please review booking database structure: columns amount and date added. 
Started to work on controller: methods new and create.
Link to the view is working.
Thanks!
> Added booking controller, booking policy, working link to the view

- app/views/dreams/new.html.erb
- app/views/dreams/show.html.erb
- app/views/pages/home.html.erb
This changes the picture on the dream card with the user's uploaded picture.
> change picture on dream card with updated one

- app/views/dreams/show.html.erb
I added add, edit and delete buttons on the dream page :)
> add buttons to add, edit and delete a booking

- app/controllers/pages_controller.rb
- app/controllers/user_controller.rb
- app/models/user.rb
- app/views/pages/profile.html.erb
- app/views/shared/_profile_picture.htlm.erb
- config/routes.rb
- db/migrate/20191120100753_add_picture_to_users.rb
- db/schema.rb
- test/controllers/user_controller_test.rb
- test/controllers/users_controller_test.rb
I have updated so that user can upload picture,please review. Thank you
> user-profile-implement

- app/assets/stylesheets/components/_card.scss
- app/views/pages/profile.html.erb
Styled the dashboard like the other webpages
> style dashboard like rest of the website

- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
> updating link,text

- app/controllers/user_controller.rb
- app/models/user.rb
Now the sign up works. 
I deleted the validation/uniqueness/scope part on the user model.
> fix the sign up bug issue

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_form-create.scss
- app/views/dreams/show.html.erb
- app/views/layouts/application.html.erb
> Frontend homeapplication

- app/assets/stylesheets/components/_form-create.scss
- app/views/dreams/edit.html.erb
- app/views/dreams/new.html.erb
Add a dream/edit a dream pages:
1. HTML - changed the h1 to "Dreamers,", updated buttons with add dream/update dream
2. SCSS - padding, black border for form, more width to container-form
> Form front end

- app/views/bookings/edit.html.erb
- app/views/bookings/new.html.erb
Edited the HTML in the booking forms (add/edit) - the h1 title is now moved inside the form, so that it shows within the border and not outside.
> adjust html in add/edit a booking forms

- app/assets/stylesheets/pages/_profile.scss
- app/views/pages/profile.html.erb
Dashboard logic is updated with comments; I used a two column grid from bootstrap.
Case 1. User is current_user (own dashboard):
it will show the posted dreams with stats, and below own dream bookings with update/delete button
Case 2. User is NOT current_user(someone else's profile)
it will only show the posted dreams, with picture, description and vibe.
> Dashboard style

- app/controllers/users_controller.rb
- app/policies/user_policy.rb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/pages/profile.html.erb
- app/views/users/edit.html.erb
- config/routes.rb
- db/migrate/20191121145445_add_photo_to_users.rb
- db/schema.rb
- test/controllers/users_controller_test.rb
- test/policies/user_policy_test.rb
Possibility to upload an avatar picture and to change nickname. 
Thanks for reviewing!
> User profile update

- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/views/bookings/edit.html.erb
- app/views/bookings/new.html.erb
- package.json
- yarn.lock
Booking#new + Booking#edit now have a calendar with minimum date set to today.
> Add datepicker to bookings

- app/controllers/application_controller.rb
- app/controllers/dreams_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/dreams/show.html.erb
- app/views/pages/profile.html.erb
- added nickname field to sign up, to be saved in database
- updated dashboard with nickname
- updated dream show with nickname
> Add nickname to signup

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_new.scss
- app/views/dreams/new.html.erb
basically nothing but pls look
> small update form

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
I fixed devise/views/sessions/new and devise/views/registrations/new to be centered.
> fix views login/signup to be centered

- app/assets/stylesheets/application.scss
flatpickr doesn't display on heroku app.
I tried to import the CSS file in the external libraries.
> will this work?

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
The stylesheet_pack_tag was still commented in HEAD of application.html.erb.
This should solve the calendar problem.
> Forgot to uncomment stylesheet pack tag in application.html.erb

- app/assets/stylesheets/components/_form-create.scss
- app/javascript/plugins/flatpickr.js
- app/views/bookings/edit.html.erb
- app/views/bookings/new.html.erb
- app/views/dreams/edit.html.erb
- app/views/dreams/new.html.erb
- app/views/users/edit.html.erb
Updated the forms with new design and typewriter effect (for new dream/edit dream)
> Form design update

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> place homepage card

- app/assets/stylesheets/components/_form-create.scss
- app/views/dreams/show.html.erb
> used margin

- app/views/pages/profile.html.erb
Fixed : user profile, in case a booking is done, information regarding client are displayed correctly.
> Bug profile fixed
